backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: trainings
    label: Trainings
    label_singular: 'Training'
    folder: content/trainings
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Sections
        name: sections
        minimize_collapsed: true
        widget: "list"
        fields:
          - { label: Section Title, name: sectionTitle, widget: string, default: "default section title" }
          - { label: pages,
              name: pages,
              minimize_collapsed: true,
              widget: list,
              fields: [
                {label: "Page Title", name: "pageTitle", widget: "string", default: "default page title"},
                {label: "Body", name: "body", widget: "markdown" }
              ]
            }
